version: '3.8'
services:
  backend:
    build: ./BACK/.
    working_dir: /usr/src/app/storeJava
    volumes:
      - ./BACK/app/.:/usr/src/app
    ports:
      - 8080:8080
      - 8081:8081
    depends_on:
      - database
    # RUN PROJECT
    # command: sh -c "mvn exec:java"
    # COMPILE PROJECT
    # command: sh -c "mvn clean install && mvn package"
    # ALL
    command: sh -c "mvn clean package && mvn exec:java"
    
  frontend:
    build: ./FRONT/.
    working_dir: /usr/src/app/vue-application
    volumes:
      - ./FRONT/app/.:/usr/src/app
    ports:
      - 8082:5137
    command: sh -c "npm install && npm run dev"

  database:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: EmpresaDB
    volumes:
      - ./DATABASE/database.sql:/docker-entrypoint-initdb.d/empresa.sql
  server:
    image: httpd:alpine
    working_dir: /usr/local/apache2/htdocs/
    volumes:
      - ./SERVER/.:/usr/local/apache2/htdocs/
    ports:
      - 80:80
